"""Init

Revision ID: a8f0812abbe0
Revises: 
Create Date: 2021-10-16 14:49:43.868548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from app.config import settings

revision = 'a8f0812abbe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True),
        sa.Column('firstname', sa.String(length=32), nullable=False),
        sa.Column('lastname', sa.String(length=64), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE')),
        sa.PrimaryKeyConstraint('id'),
        schema=settings.DB.SCHEMA,
    )

    op.create_unique_constraint(
        constraint_name='uq_firstname_lastname',
        table_name='users',
        columns=['firstname', 'lastname'],
    )

    op.create_table(
        'bonuses',
        sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True),
        sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('userid', sa.BigInteger(), nullable=False),
        sa.Column('points', sa.BigInteger(), default=0),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_index(
        index_name='ix_x5_test_bonuses_userid',
        table_name='bonuses',
        columns=['userid'],
        unique=False, schema=settings.DB.SCHEMA,
    )

    op.create_foreign_key(
        constraint_name='bonuses_userid__users_id_fkey',
        source_table='bonuses',
        local_cols=['userid'],
        referent_table='users',
        remote_cols=['id'],
        ondelete='CASCADE',
        source_schema=settings.DB.SCHEMA,
        referent_schema=settings.DB.SCHEMA,
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name='uq_firstname_lastname',
        table_name='users',
        schema=settings.DB.SCHEMA,
        type_='unique',
    )

    op.drop_constraint(
        constraint_name='bonuses_userid__users_id_fkey',
        table_name='bonuses',
        schema=settings.DB.SCHEMA,
        type_='foreignkey',
    )

    op.drop_table('users', schema=settings.DB.SCHEMA)
    op.drop_table('bonuses', schema=settings.DB.SCHEMA)
